name: Build and Release EXE

on:
  push:
    branches:
      - main
    paths:
      - link_raid_automation.py
      - requirements.txt

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set version in script
        shell: pwsh
        run: |
          $version = "v${{ github.run_number }}"
          (Get-Content link_raid_automation.py) -replace '__version__ = "vDEV"', "__version__ = `"$version`"" | Set-Content link_raid_automation.py

      - name: Create tag
        run: |
          git -c user.name="${{ github.actor }}" -c user.email="${{ github.actor }}@users.noreply.github.com" tag -a "version-${{ github.run_number }}" -m "version ${{ github.run_number }}"
          git push origin "version-${{ github.run_number }}"

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --name "link_raid_automation-v${{ github.run_number }}" link_raid_automation.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: version-${{ github.run_number }}
          files: dist/link_raid_automation-v${{ github.run_number }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
