name: Build and Release EXE

on:
  push:
    branches:
      - main
    paths:
      - link-raid-automation.py
      - requirements.txt

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "version-${{ github.run_number }}" -m "version ${{ github.run_number }}"
          git push origin "version-${{ github.run_number }}"

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --name "link-raid-automation-v${{ github.run_number }}" link-raid-automation.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: version-${{ github.run_number }}
          files: dist/link-raid-automation-v${{ github.run_number }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
